#  Numpy

In [1]:
import numpy as np

In [2]:
import time

In [9]:
size = 1000000000

In [ ]:
py_list = list(range(size))
start = time.time()
result = [x*2 for x in py_list]    # list comprehension
print(f"Python list time: {time.time() - start:.5f}s")

In [8]:
np_arr = np.arange(size)
start = time.time()
result = np_arr*2
print(f"Numpy list time: {time.time() - start:.5f}s")

Numpy list time: 0.00397s


### Creating Arrays

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [11]:
import numpy as np

In [16]:
a = np.array([1,2,3,4,5])   #1d array

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
type(a)

numpy.ndarray

In [20]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]], [[9,1],[3,4]]])

In [23]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 1],
        [3, 4]]])

In [50]:
int_arr = np.array([1,2,3], dtype=np.int32)
float_arr = np.array([1,2,3], dtype=np.float64)
bool_arr = np.array([0,1,1,1,0,0,1], dtype=bool)
comp_arr = np.array([1, 3], dtype= complex)

In [51]:
print(f"int_arr : {int_arr.dtype}")
print(f"float_arr : {float_arr.dtype}")

int_arr : int32
float_arr : float64


In [52]:
comp_arr

array([1.+0.j, 3.+0.j])

In [49]:
print(f"comp_arr : {comp_arr.dtype}")

comp_arr : complex128


In [57]:
t_arr = np.array( ((1,2,3),(4,5,6)) )

In [58]:
t_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
type(t_arr)

numpy.ndarray

In [65]:
t_arr.ndim

2

In [66]:
a3.ndim

3

In [68]:
a3.shape

(3, 2, 2)

In [72]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [73]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a.ndim

1

In [75]:
a_view = a.view()
a_copy = a.copy()

In [76]:
a_view

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array Creation Functions

In [80]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [88]:
np.ones(6,dtype=np.int64)

array([1, 1, 1, 1, 1, 1])

In [7]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [89]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye(8,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
np.arange(3,14)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [103]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [106]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [115]:
a = np.linspace(1,100, 10, dtype=np.int64)

In [116]:
a

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [117]:
len(a)

10

In [122]:
np.linspace(0,100, 10, endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [12]:
np.empty((4,4))

array([[5.38783673e-310, 0.00000000e+000, 6.71544693e-310,
        2.37663529e-312],
       [2.22809558e-312, 2.46151512e-312, 6.79038654e-313,
        2.35541533e-312],
       [2.46151512e-312, 6.79038654e-313, 2.35541533e-312,
        6.79038654e-313],
       [2.14321575e-312, 2.22809558e-312, 2.14321575e-312,
        0.00000000e+000]])

In [16]:
a = np.array([[1,4,2],[3,4,2],[5,6,7],[7,8,9]])
a

array([[1, 4, 2],
       [3, 4, 2],
       [5, 6, 7],
       [7, 8, 9]])

In [17]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [135]:
np.full((1,6),13)

array([[13, 13, 13, 13, 13, 13]])

In [19]:
np.full_like(a,13)

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

In [20]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag(np.arange(1,7), k = -2)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0]])

In [149]:
np.fromfunction(lambda i,j: i+j, (4,4), dtype=np.int32)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]], dtype=int32)

In [170]:
def abc(a,b):
    return a+b

In [171]:
np.fromfunction(abc,shape=(3,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

### Array Attributes

In [24]:
a

array([[1, 4, 2],
       [3, 4, 2],
       [5, 6, 7],
       [7, 8, 9]])

In [25]:
a.ndim

2

In [185]:
a.ndim

2

In [186]:
a.shape

(2, 3)

In [187]:
a.size

6

In [188]:
a.dtype

dtype('int64')

In [26]:
a.itemsize

8

In [27]:
a.nbytes

96

In [193]:
a=  np.arange(2,20, dtype= np.int32)

In [194]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int32)

In [41]:
a.itemsize

8

In [196]:
a.nbytes

72

In [28]:
a.size

12

In [29]:
a.strides

(24, 8)

In [30]:
a

array([[1, 4, 2],
       [3, 4, 2],
       [5, 6, 7],
       [7, 8, 9]])

In [35]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:

a = np.array([[1,2,3],[4,5,6]])

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
list(a.flat)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

In [40]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [211]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [221]:
arr = []
l = [1,2,3,4]
l1 = [4,5,6,7]
arr.append(l)
arr.append(l1)

In [222]:
arr

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [223]:
arr = np.array(arr)

In [224]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

AttributeError: 'numpy.ndarray' object has no attribute 'extend'

In [3]:
arr =  np.array([2,3,4,5,6])

In [4]:
arr

array([2, 3, 4, 5, 6])

In [42]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [47]:
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

### Casting

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.dtype

dtype('int64')

In [52]:
a = a.astype(np.float32)

In [53]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [54]:
a.dtype

dtype('float32')

In [55]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [58]:
a = np.array([1,0,0,1,1,0,30], dtype=bool)

In [59]:
a

array([ True, False, False,  True,  True, False,  True])

### Indexing & Slicing

In [110]:
a1 = np.arange(1,17)

In [111]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [112]:
a1.ndim

1

In [114]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [113]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
a.ndim

1

In [65]:
a = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [66]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [105]:
a.shape

(16,)

In [106]:
a.ndim

1

In [107]:
a = a.reshape(4,4)

In [108]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
a.ndim

2

In [115]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [119]:
print(a1[6])

7


In [121]:
print(a1[15])

16


In [122]:
a1[-1]

np.int64(16)

In [123]:
a1[-3]

np.int64(14)

In [124]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [125]:
a1[0:5]

array([1, 2, 3, 4, 5])

In [126]:
a1[6:9]

array([7, 8, 9])

In [127]:
a2 = np.arange(10)

In [128]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
a2[6] #6


np.int64(6)

In [130]:
a2[7]  #7

np.int64(7)

In [131]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a2[::2]

array([0, 2, 4, 6, 8])

In [137]:
a2[1::2]

array([1, 3, 5, 7, 9])

In [138]:
a2[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2d indexing

In [141]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [140]:
a[2,2]

np.int64(11)

In [143]:
a[1,3]

np.int64(8)

In [144]:
a[0,0]

np.int64(1)

In [145]:
a[1,0]

np.int64(5)

In [146]:
a[1]

array([5, 6, 7, 8])

In [147]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [148]:
a[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
a[:,1]

array([ 2,  6, 10, 14])

In [150]:
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [152]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [153]:
a[:,(0,1,3)]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12],
       [13, 14, 16]])

In [154]:
a[(1,2,3),:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [155]:
a[1:,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [156]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [161]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [164]:
a[2:,2:]

array([[11, 12],
       [15, 16]])

In [165]:
a[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [166]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [167]:
a[1::2,0::2]

array([[ 5,  7],
       [13, 15]])

In [170]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [171]:
a[a>10]

array([11, 12, 13, 14, 15, 16])

In [172]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [173]:
a[a%5 == 0]

array([ 5, 10, 15])

In [178]:
a[(a%2==0) & (a%3==0) & (a%6==0)]

array([ 6, 12])

In [176]:
a[(a%5 == 0) | (a%6==0)]

array([ 5,  6, 10, 12, 15])

In [181]:
a[0,0] = 22
a[3,2] = 44

In [182]:
a

array([[22,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 44, 16]])

In [184]:
a[a%6==0] = 0

In [185]:
a

array([[22,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10, 11,  0],
       [13, 14, 44, 16]])

In [188]:
a[3,0] = -34

In [189]:
a

array([[ 22,   2,   3,   4],
       [  5,   0,   7,   8],
       [  9,  10,  11,   0],
       [-34,  14,  44,  16]])

In [207]:
a = np.where(a>0, a, 'neg')

In [208]:
a

array([['22', '2', '3', '4'],
       ['5', 'neg', '7', '8'],
       ['9', '10', '11', 'neg'],
       ['neg', '14', '44', '16']], dtype='<U21')

In [209]:
a

array([['22', '2', '3', '4'],
       ['5', 'neg', '7', '8'],
       ['9', '10', '11', 'neg'],
       ['neg', '14', '44', '16']], dtype='<U21')

In [211]:
a = np.where((a=='neg'),'0', a)

In [212]:
a

array([['22', '2', '3', '4'],
       ['5', '0', '7', '8'],
       ['9', '10', '11', '0'],
       ['0', '14', '44', '16']], dtype='<U21')

In [214]:
a

array([['22', '2', '3', '4'],
       ['5', '0', '7', '8'],
       ['9', '10', '11', '0'],
       ['0', '14', '44', '16']], dtype='<U21')

In [217]:
a= a.astype(int)

In [218]:
a

array([[22,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10, 11,  0],
       [ 0, 14, 44, 16]])

In [222]:
a1 = a.reshape(2,4,2)

In [223]:
a1

array([[[22,  2],
        [ 3,  4],
        [ 5,  0],
        [ 7,  8]],

       [[ 9, 10],
        [11,  0],
        [ 0, 14],
        [44, 16]]])

In [224]:
a1.ndim

3

In [221]:
a

array([[22,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10, 11,  0],
       [ 0, 14, 44, 16]])

In [229]:
a= input().strip().split(' ')

 1 2


In [231]:
print("Helo")

Helo


In [227]:
print(f"{a}, {b}, {c}")

1, 2, 3


In [232]:
a

['1', '2']

In [233]:
b = np.array([3,4])

In [234]:
b

array([3, 4])

In [236]:
a = np.concatenate([a,b])

In [238]:
a

array(['1', '2', '3', '4'], dtype='<U21')

In [239]:
a.dtype

dtype('<U21')

In [240]:
a

array(['1', '2', '3', '4'], dtype='<U21')

In [245]:
a = a.astype(int)

In [248]:
a = np.concatenate([a,b,a,b])

In [250]:
a

array([1, 2, 3, 4, 3, 4, 1, 2, 3, 4, 3, 4])

In [252]:
a.size

12

In [253]:
a = a.reshape(4,3)

In [254]:
a

array([[1, 2, 3],
       [4, 3, 4],
       [1, 2, 3],
       [4, 3, 4]])

In [255]:
b = a.T

In [257]:
b = np.array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4], [6,5,8,9]])

In [258]:
b

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [260]:
print(f"{a.shape} \t {b.shape}")

(4, 3) 	 (4, 4)


In [261]:
np.concatenate([a,b], axis = 1)

array([[1, 2, 3, 1, 4, 1, 4],
       [4, 3, 4, 2, 3, 2, 3],
       [1, 2, 3, 3, 4, 3, 4],
       [4, 3, 4, 6, 5, 8, 9]])

In [263]:
a

array([[1, 2, 3],
       [4, 3, 4],
       [1, 2, 3],
       [4, 3, 4]])

In [264]:
b

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [265]:
a.reshape(3,4)

array([[1, 2, 3, 4],
       [3, 4, 1, 2],
       [3, 4, 3, 4]])

In [266]:
a = a.T

In [267]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4]])

In [268]:
b

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [269]:
np.concatenate([a,b],axis=0)

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [281]:
a = np.array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],[7,5,3,1]])

In [282]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [283]:
b

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [285]:
np.stack([a,b])


array([[[1, 4, 1, 4],
        [2, 3, 2, 3],
        [3, 4, 3, 4],
        [7, 5, 3, 1]],

       [[1, 4, 1, 4],
        [2, 3, 2, 3],
        [3, 4, 3, 4],
        [6, 5, 8, 9]]])

In [287]:
np.stack([a,b], axis=1)

array([[[1, 4, 1, 4],
        [1, 4, 1, 4]],

       [[2, 3, 2, 3],
        [2, 3, 2, 3]],

       [[3, 4, 3, 4],
        [3, 4, 3, 4]],

       [[7, 5, 3, 1],
        [6, 5, 8, 9]]])

In [288]:
np.vstack([a,b])

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1],
       [1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [289]:
np.hstack([a,b])

array([[1, 4, 1, 4, 1, 4, 1, 4],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [7, 5, 3, 1, 6, 5, 8, 9]])

In [290]:
np.dstack([a,b])

array([[[1, 1],
        [4, 4],
        [1, 1],
        [4, 4]],

       [[2, 2],
        [3, 3],
        [2, 2],
        [3, 3]],

       [[3, 3],
        [4, 4],
        [3, 3],
        [4, 4]],

       [[7, 6],
        [5, 5],
        [3, 8],
        [1, 9]]])

### Split

In [292]:
print(np.split(a,4))

[array([[1, 4, 1, 4]]), array([[2, 3, 2, 3]]), array([[3, 4, 3, 4]]), array([[7, 5, 3, 1]])]


In [293]:
a1 = np.array([1,2,3,4,5,6,7,8,9])

In [294]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [295]:
np.split(a1,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [298]:
np.split(a1,9)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

In [301]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [302]:
np.split(a1, [2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [300]:
print(f"{a1[:3]}\n{a1[3:8]}\n{a1[8:]}")

[1 2 3]
[4 5 6 7 8]
[9]


In [304]:
np.split(a1, [3])

[array([1, 2, 3]), array([4, 5, 6, 7, 8, 9])]

In [305]:
np.split(a1, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [306]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [307]:
np.vsplit(a,2)

[array([[1, 4, 1, 4],
        [2, 3, 2, 3]]),
 array([[3, 4, 3, 4],
        [7, 5, 3, 1]])]

In [308]:
np.hsplit(a,2)

[array([[1, 4],
        [2, 3],
        [3, 4],
        [7, 5]]),
 array([[1, 4],
        [2, 3],
        [3, 4],
        [3, 1]])]

### Arithmatic Operations

In [309]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [310]:
b

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [311]:
a+b

array([[ 2,  8,  2,  8],
       [ 4,  6,  4,  6],
       [ 6,  8,  6,  8],
       [13, 10, 11, 10]])

In [312]:
a-b

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 1,  0, -5, -8]])

In [313]:
a*b

array([[ 1, 16,  1, 16],
       [ 4,  9,  4,  9],
       [ 9, 16,  9, 16],
       [42, 25, 24,  9]])

In [314]:
a/b

array([[1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.16666667, 1.        , 0.375     , 0.11111111]])

In [315]:
a**b

array([[     1,    256,      1,    256],
       [     4,     27,      4,     27],
       [    27,    256,     27,    256],
       [117649,   3125,   6561,      1]])

In [316]:
b[1,1] = 0

In [317]:
b

array([[1, 4, 1, 4],
       [2, 0, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [318]:
a/b

/tmp/ipykernel_16771/1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([[1.        , 1.        , 1.        , 1.        ],
       [1.        ,        inf, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.16666667, 1.        , 0.375     , 0.11111111]])

In [319]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [320]:
a+10

array([[11, 14, 11, 14],
       [12, 13, 12, 13],
       [13, 14, 13, 14],
       [17, 15, 13, 11]])

In [321]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [322]:
a*4

array([[ 4, 16,  4, 16],
       [ 8, 12,  8, 12],
       [12, 16, 12, 16],
       [28, 20, 12,  4]])

In [323]:
np.add(a,b)

array([[ 2,  8,  2,  8],
       [ 4,  3,  4,  6],
       [ 6,  8,  6,  8],
       [13, 10, 11, 10]])

In [324]:
np.multiply(a,b)

array([[ 1, 16,  1, 16],
       [ 4,  0,  4,  9],
       [ 9, 16,  9, 16],
       [42, 25, 24,  9]])

In [325]:
b[1,1] = -4

In [326]:
b

array([[ 1,  4,  1,  4],
       [ 2, -4,  2,  3],
       [ 3,  4,  3,  4],
       [ 6,  5,  8,  9]])

In [327]:
np.absolute(b)

array([[1, 4, 1, 4],
       [2, 4, 2, 3],
       [3, 4, 3, 4],
       [6, 5, 8, 9]])

In [328]:
b

array([[ 1,  4,  1,  4],
       [ 2, -4,  2,  3],
       [ 3,  4,  3,  4],
       [ 6,  5,  8,  9]])

In [329]:
a+10

array([[11, 14, 11, 14],
       [12, 13, 12, 13],
       [13, 14, 13, 14],
       [17, 15, 13, 11]])

In [330]:
row = np.array([10,11,15,45])

In [331]:
row

array([10, 11, 15, 45])

In [332]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [333]:
a+row

array([[11, 15, 16, 49],
       [12, 14, 17, 48],
       [13, 15, 18, 49],
       [17, 16, 18, 46]])

In [334]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [337]:
np.exp2(a)

array([[  2.,  16.,   2.,  16.],
       [  4.,   8.,   4.,   8.],
       [  8.,  16.,   8.,  16.],
       [128.,  32.,   8.,   2.]])

In [338]:
np.sqrt(a)

array([[1.        , 2.        , 1.        , 2.        ],
       [1.41421356, 1.73205081, 1.41421356, 1.73205081],
       [1.73205081, 2.        , 1.73205081, 2.        ],
       [2.64575131, 2.23606798, 1.73205081, 1.        ]])

In [339]:
np.cbrt(a)

array([[1.        , 1.58740105, 1.        , 1.58740105],
       [1.25992105, 1.44224957, 1.25992105, 1.44224957],
       [1.44224957, 1.58740105, 1.44224957, 1.58740105],
       [1.91293118, 1.70997595, 1.44224957, 1.        ]])

In [340]:
np.power(a,3)

array([[  1,  64,   1,  64],
       [  8,  27,   8,  27],
       [ 27,  64,  27,  64],
       [343, 125,  27,   1]])

In [341]:
np.nan

nan

In [343]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [344]:
np.sum(a)

np.int64(50)

In [345]:
np.min(a)

np.int64(1)

In [347]:

np.max(a)

np.int64(7)

In [348]:
np.argmax(a)

np.int64(12)

In [349]:
np.mean(a)

np.float64(3.125)

In [351]:
np.sort(a1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [352]:
np.sort(a)

array([[1, 1, 4, 4],
       [2, 2, 3, 3],
       [3, 3, 4, 4],
       [1, 3, 5, 7]])

In [353]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [354]:
np.searchsorted(a1,4)

np.int64(3)

In [355]:
a1[3]

np.int64(4)

In [356]:
np.searchsorted(a,7)

ValueError: object too deep for desired array

In [150]:
a2 = np.array([1,2])
b2 = np.array([3,4])

In [151]:
a2

array([1, 2])

In [152]:
b2

array([3, 4])

In [153]:
a2 @ b2 

np.int64(11)

In [154]:
np.matmul(a2,b2)

np.int64(11)

In [155]:
np.dot(a2,b2)

np.int64(11)

In [157]:
np.inner(a2,b2)

np.int64(11)

In [158]:
np.outer(a2,b2)

array([[3, 4],
       [6, 8]])

In [364]:
a

array([[1, 4, 1, 4],
       [2, 3, 2, 3],
       [3, 4, 3, 4],
       [7, 5, 3, 1]])

In [366]:
np.trace(a)

np.int64(8)

In [367]:
e_a = np.array([])

In [368]:
e_a

array([], dtype=float64)

In [379]:
r1 = [1,2,3,4]


In [380]:
r2 = [5,3,2,6]


In [378]:
t = []

In [381]:
t.append(r1)
t.append(r2)

In [382]:
t

[[1, 2, 3, 4], [5, 3, 2, 6]]

In [6]:
n,m = input().strip().split()

ar = np.array([input().split() for _ in range(int(n))], dtype=int)

 2 2
 1 2
 3 4


In [7]:
ar

array([[1, 2],
       [3, 4]])

### Vectorization

In [8]:
arr =  np.array([-1,-3,4,5,0, -2])

In [9]:
arr

array([-1, -3,  4,  5,  0, -2])

In [10]:
def classify(a):
    if a<0:
        return 'neg'
    elif a==0:
        return 'zero'
    else:
        return 'pos'

In [16]:
new_l = []
for i in arr:
    new_l.append(classify(i))
print(new_l)

['neg', 'neg', 'pos', 'pos', 'zero', 'neg']


In [12]:
classifier = np.vectorize(classify)

In [13]:
print(classifier(arr))

['neg' 'neg' 'pos' 'pos' 'zero' 'neg']


In [17]:
def abc():
    print("hello")

In [18]:
abc()

hello


In [19]:
hel = abc

In [20]:
hel()

hello


### Random module

In [102]:
np.random.seed(31)
l = [np.random.randint(1,20) for i in range(10)]
print(l)

[19, 17, 3, 7, 11, 15, 7, 19, 19, 18]


In [119]:
r = np.random.default_rng(40)
l1 = [r.integers(1,100) for _ in range(10)]
print(l1)

[np.int64(56), np.int64(73), np.int64(3), np.int64(69), np.int64(44), np.int64(94), np.int64(4), np.int64(6), np.int64(47), np.int64(69)]


In [120]:
normal = r.standard_normal(size=1000)


In [126]:
print(f"{normal.mean():.4f}")

-0.0233


In [127]:
arr

array([-1, -3,  4,  5,  0, -2])

In [133]:
np.random.choice(arr)

np.int64(0)

In [139]:
a = input().split()

 2 3


In [140]:
a

['2', '3']

In [141]:
n,m = a

In [142]:
n

'2'

In [143]:
m

'3'

In [192]:
print(np.random.randint(4,6))

4


In [194]:
np.array([x for x in range(2, 10) if x%2!=0]) # Your code here

array([3, 5, 7, 9])